Repository setnemo/autogenerated-messages, pull requests merged in 2023-10, with the labels that each got.

#36 feat: adds laravel starts_with and ends_with validations
  src/ValidationMessages/DefaultMessages.php
  src/ValidationMessages/ValidationConstant.php
  tests/Unit/DefaultMessageTest.php
Labels: hacktoberfest, pull_request_target

#38 feat: adds laravel doesnt_start_with and doesnt_end_with validations
  src/ValidationMessages/DefaultMessages.php
  src/ValidationMessages/ValidationConstant.php
  tests/Unit/DefaultMessageTest.php
Labels: hacktoberfest, pull_request_target, hacktoberfest-accepted

#41 docs: README.md update supported validations
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#40 feat: adds laravel multiple_of validations
  src/ValidationMessages/DefaultMessages.php
  src/ValidationMessages/ValidationConstant.php
  tests/Unit/DefaultMessageTest.php
Labels: hacktoberfest, hacktoberfest-accepted

#42 feat: add same validation message
  src/ValidationMessages/DefaultMessages.php
  src/ValidationMessages/ValidationConstant.php
  tests/Unit/DefaultMessageTest.php
Labels: hacktoberfest, hacktoberfest-accepted
